spring:
  application:
    name: books
  profiles:
    default: dev

server:
  port: 8082

app:
  activation:
    email:
      from: noreply@example.com
      subject: "Activate your account"
      base-url: http://localhost:3000
